### ISSUE TITLE
Memecaptain api down?

### ISSUE THREAD

**Issue by kellyschoenhofen** [mmb/meme_captain_web#3]
All of our generated images - http://v1.memecaptain.com/d71383.jpg for instance - have been returning a Error 503 Service Unavailable since last week. Was there an API change, or this a known outage, or?

**Comment by mmb** [comment]
Thanks for reporting. This should be fixed now.

v1.memecaptain.com is on an older server that isn't as robust as the new ones. Although it sounds like you are primarily an API user and the new (v2) code does not focus on API as much as the v1 code.

**Comment by kellyschoenhofen** [comment]
Woot! We're back up! And productive again!

What should we do? Is there a new API we should transition to?

**Comment by mmb** [comment]
I'm working on adding an API to the new site (memecaptain.com), which performs better and is more stable. The v1.memecaptain.com API will be deprecated at some point after the new one is finished.

**Comment by corbanmailloux** [comment]
Is the v1 API down again? 
HipChat's "Sassy" bot is returning "Sorry, the memecaptain.com API appears to be unavailable" and our old v1 links all appear to be broken.

Thanks.

**Comment by kellyschoenhofen** [comment]
Prior to v1 api going down, I did let the sassy people know - https://bitbucket.org/atlassianlabs/ac-koa-hipchat-sassy/issue/6/sassy-is-depressed-and-suicidal#comment-18662491

No response. (sadpanda)

**Comment by corbanmailloux** [comment]
(sadpanda) indeed.

Well thanks for following up.
