### ISSUE TITLE
Uploading a new source image using byte or base64 encoded?

### ISSUE THREAD

**Issue by asakurastar** [mmb/meme_captain_web#6]
First of all, thanks for this API, it's working like a charm. 

I've been using on my personal android application to create memes and share on Facebook with no problems so far.

Now i want to expand by creating my own images instead using existing ones.
I know it is possible to create new source images by using the /src_images endpoint but only with URL as source.

What i want to do is choose an image from my android pictures gallery and upload to the Memecaptain. 
This could be possible if MemeCaptain API accept the byte content or maybe a base64 encoded data from the image itself.

JSON Example:

    {
        data : "data:image/png,base64,iVBORw0KGgoAAAANSUhEUgAAA98AAAMmCAQAAABGZ/rqAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAAlwSFlzA...",
        name : "My cool meme",
        private : false
    }

Is it possible?
Thanks and sorry for my bad english.

**Comment by mmb** [comment]
You should be able to use a data URI like the one in your example in the `url` field. This is a relatively new feature so please open an issue if you run into any problems.
